# KNN - Regressor

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sns

import warnings 
warnings.filterwarnings('ignore')

In [44]:
from sklearn.datasets import make_regression

x, y = make_regression(n_samples=1000, n_features=3, noise=10, random_state=1)


In [45]:
x

array([[ 1.45167891,  0.3416886 , -0.12517266],
       [-0.7003985 , -0.20339445,  0.24266944],
       [-0.10646012, -2.79099641, -0.45611756],
       ...,
       [-0.56282904, -1.2514994 ,  1.29857162],
       [-1.16896134, -1.8994631 , -2.5399554 ],
       [ 0.88608992,  0.31897183,  0.26486763]])

In [46]:
y

array([ 1.30413977e+02, -6.21867947e+01, -2.86897524e+02,  7.26953562e+01,
        5.40392780e+01,  1.61526999e+02,  2.12722597e+02,  1.49784253e+01,
       -4.36084039e+02, -1.62326969e+02,  6.02345736e+01,  2.02191512e+02,
       -9.45417105e+01,  9.47409260e+01, -2.92795352e+02,  7.07463804e+01,
       -1.56571745e+02,  1.12529115e+02,  1.19568828e+02, -1.41554572e+02,
       -1.84532632e+02,  1.21844031e+02, -1.89548300e+01, -7.91415124e+01,
       -6.63768542e+01, -1.53878430e+02,  1.92850090e+02,  1.00480781e+01,
       -8.23935431e+01, -8.47004890e+01,  1.62850902e+02, -7.25359267e+01,
       -9.25519522e+01,  8.66293747e+01,  2.46654572e+02, -2.39017264e+02,
        2.95272579e+02, -4.21652641e+01,  2.65361429e+02,  1.84670049e+02,
       -1.18656998e+01, -3.06309166e+02, -2.65007757e+02,  1.19864587e+01,
        1.48627245e+02, -7.79097272e+01, -1.42818652e+01,  3.53912117e+02,
       -9.29029114e+01,  5.07721732e+01, -2.54042273e+01,  1.66696947e+02,
        6.24816272e+01,  

In [47]:
from sklearn.model_selection import train_test_split

# split the data int x and y datasets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

In [48]:
x_train.shape, x_test.shape

((700, 3), (300, 3))

In [49]:
# creation of model
from sklearn.neighbors import KNeighborsRegressor

reg =  KNeighborsRegressor()

In [50]:
reg

KNeighborsRegressor()

In [52]:
reg.fit(x_train, y_train)

KNeighborsRegressor()

In [53]:
y_pred = reg.predict(x_test)
y_pred

array([ -56.8968639 ,  -17.74398138, -107.49967537,   -0.78859479,
         -4.00756521,    5.10134569,  272.1672113 ,  -53.83218825,
        131.17876375,   12.23818993, -177.2139075 ,   -2.08230229,
        156.52718859,    2.83185973, -159.5863408 ,   61.32492923,
       -189.9133695 ,  194.27254226,  -43.63508874,   19.79537687,
        147.85505877,  113.10947629, -105.49395643,  -36.52130316,
        -26.06778671,  320.36878111,  183.67148528,   26.56747097,
          6.4353237 ,   83.14072422,  -83.40240102,  -10.99937444,
        -65.34778301,  279.17817657,  -21.01579869, -193.74346262,
        136.63432427,  204.59399308,  -17.38617295,  172.60941667,
          3.82083554,  159.89143646,   32.0403207 , -218.36959186,
       -225.95850489,  -11.68178209, -214.13611628, -263.27699632,
       -111.64804288,  138.91935452, -224.40021336,  240.07010714,
         -9.96798665, -191.52992751,  226.47094253,  116.17629807,
          8.6275754 ,  -66.16756172,  146.1764226 , -109.02676

In [55]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
print(r2_score(y_test, y_pred))

0.967482699474131


In [56]:
print(mean_absolute_error(y_test, y_pred))

21.2033002743734


In [57]:
print(mean_squared_error(y_test, y_pred))

860.918539493994


In [58]:
# hyperparameter tuning

from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_neighbors' : [3, 5, 6, 7, 9, 11, 13],
    'weights' : ['uniform', 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size' : [20, 30, 40, 50]
}

In [59]:
grid_search = GridSearchCV(estimator=reg,param_grid=param_grid, cv=5, verbose=3 )
grid_search

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [60]:
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 224 candidates, totalling 1120 fits
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.959 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.969 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.963 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.974 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.953 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.963 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.971 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.966 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, 

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [61]:
grid_search.best_params_

{'algorithm': 'auto', 'leaf_size': 20, 'n_neighbors': 3, 'weights': 'distance'}

In [62]:
grid_search.best_score_

np.float64(0.9671265606863997)