# Ensemble Technique

# Bagging Regressor or Hard Voting Regressor

In [40]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings 
warnings.filterwarnings('ignore')

In [42]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split


In [44]:
X, y = make_regression(n_samples = 100, n_features = 10, noise = 0.1, random_state = 1 )

In [45]:
X

array([[ 2.42669441e-01, -1.20464572e-01,  2.01830179e-01,
         1.79215821e+00,  6.61020288e-01, -1.23312074e+00,
        -1.67419581e+00,  8.25029824e-01, -6.65754518e-01,
        -1.18231813e+00],
       [-3.10116774e-01,  4.41364444e-01, -2.43483776e+00,
         2.18697965e+00,  1.03882460e+00, -1.00155233e-01,
         1.74094083e-02, -1.12201873e+00, -1.19054188e-01,
        -1.36444744e-01],
       [-3.43900709e-01, -6.93286967e-02, -1.00016919e+00,
         6.08514698e-01,  1.04499441e+00, -1.08392067e-01,
         8.70969803e-01, -5.08457134e-01,  1.76533510e+00,
         4.50155513e-01],
       [ 1.69380911e+00,  6.93366226e-01,  1.96869779e-01,
        -1.16400797e+00,  1.69869255e-01, -7.58067329e-01,
         1.81038744e-01,  1.10717545e+00,  5.57439453e-01,
        -8.08847196e-01],
       [-1.90548298e-01, -9.48439656e-01,  2.33339126e-01,
         9.10423603e-01,  4.34998324e-01, -4.23478297e-01,
         4.48380651e-01,  1.12532350e+00,  3.92334911e-01,
         1.

In [46]:
y

array([ 105.12799067,   -3.92177591,   45.77207438,   28.00586057,
        225.98690724,   88.79113009,   49.88222414,  -48.14054417,
       -211.34444226,  103.25035987,  335.18401021, -287.58842127,
       -369.94180356,  242.69733289,   53.88810518,  322.03892388,
        -47.77338991,   55.62838417,  122.20369244,  113.03220559,
       -216.08161075,  128.13781681,  -44.6207825 ,  -61.81039454,
        158.16544064,  191.85374679,   98.5275681 ,  -56.55279356,
        180.89922355, -315.09397311,   21.32373723,  171.20227429,
        106.09416505,  254.84712603,   71.79001226,  -15.43400509,
        -99.36517438,  -75.61880085,  -27.54055177,  169.31113389,
        -11.41313612,  203.79630082, -133.20294417, -223.03086506,
        -89.84783898,   13.0881445 ,    7.56397778,  -59.88618599,
        -86.94925554, -128.30791895,  347.27881851,   84.09590432,
        132.73031198,  314.2103544 ,  369.07467316,  177.91362405,
        227.35298547, -133.50020483,   77.11213977,  -47.91474

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [48]:
X_train.shape, X_test.shape

((70, 10), (30, 10))

In [49]:
y_train.shape, y_test.shape

((70,), (30,))

In [51]:
# for model creation
 
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR


In [54]:
# for model creation
lr = LinearRegression()
dtr = DecisionTreeRegressor()
svr = SVR(kernel = 'linear')

In [55]:
# to create  esembles

from sklearn.ensemble import VotingRegressor
ensemble_regressor = VotingRegressor(estimators = [('linear_reg', lr), ('DTR', dtr), ('SVR', svr)])

In [56]:
ensemble_regressor

VotingRegressor(estimators=[('linear_reg', LinearRegression()),
                            ('DTR', DecisionTreeRegressor()),
                            ('SVR', SVR(kernel='linear'))])

In [58]:
# model traing

ensemble_regressor.fit(X_train, y_train)

VotingRegressor(estimators=[('linear_reg', LinearRegression()),
                            ('DTR', DecisionTreeRegressor()),
                            ('SVR', SVR(kernel='linear'))])

In [63]:
# model prediction

y_pred = ensemble_regressor.predict(X_test)  # avg. of all the prediction will be final prediction
y_pred

array([ -70.30820447,   -3.55899483,  -18.1833497 ,   80.17117873,
         88.29808167,   43.85878206,  -54.72183721,  -97.44628551,
        -22.0906658 ,   -2.63100935,  -50.19347413,   81.93288554,
        138.16248952,  138.43165576,   33.9268802 ,   91.31458071,
        106.10370763,  -66.24285414,   63.63985607,  217.98263174,
         -9.04878284,  316.3656054 , -112.87126513,  -41.87277743,
         84.07579363,   19.21421562,   46.63926132,  -46.51320297,
         45.27817011,   34.85165191])

In [64]:
# model evalution 

from sklearn.metrics import r2_score
r2_score(y_pred, y_test)

0.35658424584597637