Implementation of KNN classifier with Hyperparameter tuning

# KNN classifier

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sns

import warnings 
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_classification

x, y = make_classification(n_samples=1000, n_features=3, n_redundant=0, n_classes=2, random_state=1)


In [3]:
x.shape

(1000, 3)

In [4]:
y.shape

(1000,)

In [5]:
y

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,

In [6]:
from sklearn.model_selection import train_test_split

# split the data int x and y datasets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

In [7]:
x_train.shape, x_test.shape

((700, 3), (300, 3))

In [8]:
y_train.shape, y_test.shape

((700,), (300,))

In [9]:
# creation of model
from sklearn.neighbors import KNeighborsClassifier

In [12]:

knn_clf = KNeighborsClassifier()
knn_clf

KNeighborsClassifier()

In [13]:
knn_clf.fit(x_train, y_train)

KNeighborsClassifier()

In [14]:
# evalution of model
y_pred = knn_clf.predict(x_test)

In [15]:
y_pred

array([1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1])

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred))

[[122  23]
 [ 21 134]]


In [17]:
print(accuracy_score(y_test, y_pred))

0.8533333333333334


In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.84      0.85       145
           1       0.85      0.86      0.86       155

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



In [19]:
# hyperparametr tuning

from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_neighbors' : [3, 5, 6, 7, 9, 11, 13],
    'weights' : ['uniform', 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size' : [20, 30, 40, 50]
}

In [20]:
grid_search = GridSearchCV(estimator=knn_clf,param_grid=param_grid, cv=5, verbose=3 )

In [21]:
grid_search

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [22]:
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 224 candidates, totalling 1120 fits
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.871 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.850 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.814 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.814 total time=   0.0s
[CV 5/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=uniform;, score=0.793 total time=   0.0s
[CV 1/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.857 total time=   0.0s
[CV 2/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.836 total time=   0.0s
[CV 3/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, score=0.807 total time=   0.0s
[CV 4/5] END algorithm=auto, leaf_size=20, n_neighbors=3, weights=distance;, 

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [35]:
grid_search.best_params_

{'algorithm': 'auto', 'leaf_size': 20, 'n_neighbors': 11, 'weights': 'uniform'}

In [36]:
grid_search.best_score_

np.float64(0.8514285714285714)

In [29]:
# predict wit the best_estimaator
best_model
y_pred_tuned = grid_search.predict(x_test)

In [31]:
y_pred_tuned

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print(confusion_matrix(y_test, y_pred_tuned))

[[124  21]
 [ 19 136]]


In [33]:
print(accuracy_score(y_test, y_pred_tuned))

0.8666666666666667


In [34]:
print(classification_report(y_test, y_pred_tuned))

              precision    recall  f1-score   support

           0       0.87      0.86      0.86       145
           1       0.87      0.88      0.87       155

    accuracy                           0.87       300
   macro avg       0.87      0.87      0.87       300
weighted avg       0.87      0.87      0.87       300

