# Multiple model training, Pipeline and column Transformer IN regression porblem

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [25]:
df = sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
# Questions >> predict totall_bill >> target variable
# using Regression problems

In [29]:
# EDA >> subjective

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [31]:
x = df.drop('total_bill', axis = 1)
y = df["total_bill"]  # target variable

In [32]:
x

tip     sex smoker   day    time  size
0    1.01  Female     No   Sun  Dinner     2
1    1.66    Male     No   Sun  Dinner     3
2    3.50    Male     No   Sun  Dinner     3
3    3.31    Male     No   Sun  Dinner     2
4    3.61  Female     No   Sun  Dinner     4
..    ...     ...    ...   ...     ...   ...
239  5.92    Male     No   Sat  Dinner     3
240  2.00  Female    Yes   Sat  Dinner     2
241  2.00    Male    Yes   Sat  Dinner     2
242  1.75    Male     No   Sat  Dinner     2
243  3.00  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [33]:
y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [34]:
# split the data tarin and test data

from sklearn.model_selection import train_test_split

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state=1)

In [36]:
x_train.shape, x_test.shape

((195, 6), (49, 6))

In [37]:
y_train.shape, y_test.shape

((195,), (49,))

In [39]:
# handling the missiong value >> both categorical and numerical data
# data encoding >> only for categorical data
# feature scaling >> only for numerical data


from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler


from sklearn.pipeline import Pipeline # a sequence of data transformer
from sklearn.compose import ColumnTransformer 
# group all the pipeline steps for each of the columns


In [40]:
# seperate the categorical and numerical columns

df.sample(1)

total_bill  tip   sex smoker  day    time  size
36       16.31  2.0  Male     No  Sat  Dinner     3

In [41]:
cat_cols = ["sex", "smoker", "day", "time"]
num_cols = ["tip", "size",]

In [48]:
# feature engineering automation  using pipeline and columntransformer

num_pipeline = Pipeline(steps = [('imputation', SimpleImputer(strategy = 'median')),
                                ('scaling', StandardScaler())])

cat_pipeline = Pipeline(steps = [('imputation',SimpleImputer(strategy = 'most_frequent')),
                                ('encoding', OneHotEncoder())])

In [63]:
preprocessor = ColumnTransformer([('num_pipeline', num_pipeline, num_cols),
                                 ('cat_pipeline', cat_pipeline, cat_cols)])
preprocessor

ColumnTransformer(transformers=[('num_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['tip', 'size']),
                                ('cat_pipeline',
                                 Pipeline(steps=[('imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder())]),
                                 ['sex', 'smoker', 'day', 'time'])])

In [50]:
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [51]:
x_train

array([[-1.47443803, -0.57766863,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.71612531,  1.47042924,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 1.19880579,  1.47042924,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.43283335, -0.57766863,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       [-1.29060464, -0.57766863,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.1034652 ,  0.44638031,  1.        , ...,  0.        ,
         1.        ,  0.        ]])

In [52]:
x_test

array([[-1.48209775, -1.60171757,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [ 0.04984713, -0.57766863,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         1.        ,  0.        ],
       [ 0.36389583,  0.44638031,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-0.33313909, -0.57766863,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.04984713, -0.57766863,  0.        ,  1.        ,  1.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [-1.14506988, -0.57766863,  0.        ,  1.        ,  0.        ,
         1.        ,  

In [55]:
# now preper the train test data
# so now we will build the regressor model

from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor


In [57]:
models = {"support vector regressor" : SVR(),
         "DT Regressor" : DecisionTreeRegressor(),
         "Multiple linear Regression" : LinearRegression(),
         "Random Forest Regressor" : RandomForestRegressor()}
models 

{'support vector regressor': SVR(),
 'DT Regressor': DecisionTreeRegressor(),
 'Multiple linear Regression': LinearRegression(),
 'Random Forest Regressor': RandomForestRegressor()}

In [60]:
from sklearn.metrics import r2_score

def model_train_eval(x_train, x_test, y_trian, y_test, models):
    evalution = {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(x_train, y_train)
        y_pred = model.predict(x_test)
        model_score = r2_score(y_pred, y_test)
        evalution[list(models.keys())[i]] = model_score
    return evalution

In [62]:
model_train_eval(x_train, x_test, y_train, y_test, models)

{'support vector regressor': -2.0639738700067807,
 'DT Regressor': 0.044935725872876864,
 'Multiple linear Regression': 0.4796560973904095,
 'Random Forest Regressor': 0.30026976329923605}

# Random forest

In [75]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf

RandomForestRegressor()

In [76]:
x_train, x_test

(array([[-1.47443803, -0.57766863,  1.        , ...,  0.        ,
          1.        ,  0.        ],
        [-0.71612531,  1.47042924,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        [ 1.19880579,  1.47042924,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        ...,
        [ 0.43283335, -0.57766863,  1.        , ...,  1.        ,
          0.        ,  1.        ],
        [-1.29060464, -0.57766863,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        [ 0.1034652 ,  0.44638031,  1.        , ...,  0.        ,
          1.        ,  0.        ]]),
 array([[-1.48209775, -1.60171757,  1.        ,  0.        ,  0.        ,
          1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
          1.        ,  0.        ],
        [ 0.04984713, -0.57766863,  1.        ,  0.        ,  1.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
          1.        ,  0.        ],
     

In [81]:
# here we doing haperparameter tunning because here a lot of parameter

from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

params = {'max_depth' : [1,50, 100, 150, 200],
         'n_estimators' : [50, 100, 200],
         }
params

{'max_depth': [1, 50, 100, 150, 200], 'n_estimators': [50, 100, 200]}

In [85]:
reg= RandomizedSearchCV(rf, param_distributions=params, cv=5, verbose=3, scoring = 'r2', n_iter=10)

In [86]:
reg

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(),
                   param_distributions={'max_depth': [1, 50, 100, 150, 200],
                                        'n_estimators': [50, 100, 200]},
                   scoring='r2', verbose=3)

In [87]:
reg.fit(x_train, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV 1/5] END ...max_depth=150, n_estimators=200;, score=0.319 total time=   0.5s
[CV 2/5] END ...max_depth=150, n_estimators=200;, score=0.503 total time=   0.4s
[CV 3/5] END ...max_depth=150, n_estimators=200;, score=0.255 total time=   0.4s
[CV 4/5] END ...max_depth=150, n_estimators=200;, score=0.623 total time=   0.3s
[CV 5/5] END ...max_depth=150, n_estimators=200;, score=0.327 total time=   0.4s
[CV 1/5] END ....max_depth=50, n_estimators=200;, score=0.320 total time=   0.4s
[CV 2/5] END ....max_depth=50, n_estimators=200;, score=0.481 total time=   0.4s
[CV 3/5] END ....max_depth=50, n_estimators=200;, score=0.234 total time=   0.5s
[CV 4/5] END ....max_depth=50, n_estimators=200;, score=0.576 total time=   0.5s
[CV 5/5] END ....max_depth=50, n_estimators=200;, score=0.348 total time=   0.4s
[CV 1/5] END .....max_depth=1, n_estimators=100;, score=0.220 total time=   0.1s
[CV 2/5] END .....max_depth=1, n_estimators=100;

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(),
                   param_distributions={'max_depth': [1, 50, 100, 150, 200],
                                        'n_estimators': [50, 100, 200]},
                   scoring='r2', verbose=3)

In [88]:
reg.best_params_

{'n_estimators': 200, 'max_depth': 150}

In [89]:
reg.best_score_

np.float64(0.40532658785523223)